db.emp5.insertMany([
  {
    id: 1,
    name: 'Иван',
    surname: 'Иванов',
    fatherName: 'Иванович',
    email: 'ivan@gmail.com',
    phoneNumber: '8(777)111-11-11',
    birthDate: 'Дата рождения: 10.10.1987.  Увлечения: плавание',
    hobbies: [],
    document: 'шахматы',
  },
  {
    id: 2,
    name: 'Николай',
    surname: 'Семерук',
    fatherName: 'Александрович',
    email: 'killer@rambler.ru',
    phoneNumber: '7(777)523-68-91',
    birthDate: 'Увлечения: бокс',
    hobbies: [],
    document: 'Номер приказа: 1001',
  },
  {
    id: 3,
    name: 'Александр',
    surname: 'Хопта',
    fatherName: 'Петрович',
    email: 'sasha@.ru',
    phoneNumber: '(2-20-47)',
    birthDate: 'Увлечения: плавание',
    hobbies: [],
    document: 'Номер распоряжения: 202',
  },
  {
    id: 4,
    name: 'Владимир',
    surname: 'Никифоров',
    fatherName: 'Александрович',
    email: 'vova@rambler.ru',
    phoneNumber: '2-45-48',
    birthDate: 'Дата рождения: 12.07.1967',
    hobbies: [],
    document: 'Номер приказа: 404',
  },
  {
    id: 5,
    name: 'Семен',
    surname: 'Лобанов',
    fatherName: 'Иванович',
    email: 'semen@yandex.com',
    phoneNumber: '8(777)654-12-21',
    birthDate: 'Увлечения: борьба',
    hobbies: [],
    document: 'Номер приказа: 15',
  },
  {
    id: 6,
    name: 'Глеб',
    surname: 'Кисегач',
    fatherName: 'Викторович',
    email: 'gleb@mail.',
    phoneNumber: '2-87-98',
    birthDate: 'Увлечения:компьютерные игры',
    hobbies: [],
    document: 'Номер распоряжения: 333',
  },
  {
    id: 7,
    name: 'Варя',
    surname: 'Черноус',
    fatherName: 'Петрович',
    email: 'cher@mail.ru',
    phoneNumber: NULL,
    birthDate: 'Дата рождения: 14.01.1980',
    hobbies: [],
    document: 'Номер приказа: 1',
  },
]);
